"""BugsInPy valid-bug gate — the shared "is this bug runnable?" oracle.

Extraction for BugsInPy is recovered incrementally, so not every synced
``data/BIP/processed/<Project>/<BugId>/`` dir has complete, valid prior-step
outputs. Every BIP-aware pipeline stage (Agent4SR ``corpus``/``run``/``combine``
and Agent4LR ``run``) must gate on the **same** definition of "runnable" before
touching a bug — never feed a stage an empty or D4J-defaulted input.

The gate reads on-disk outputs only (no checkout):

* :func:`classify_bip_bug` — the extraction completeness audit (status must be in
  :data:`~src.extraction.bip_audit.COMPLETE_STATUSES`).
* :func:`bip_corpus_exists` — the SR corpus (``FlexFL/SR/corpus_methods.txt``) is present.
* :func:`bip_run_skip_reason` — combines both: ``None`` when ready, else a one-line reason.

This module was factored out of ``run_agent4sr.py`` so Agent4SR and
Agent4LR share one definition; behaviour is unchanged.
"""

from __future__ import annotations

from src.common.config import FLEXFL_SR_SUBDIR, get_processed_dir
from src.extraction.bip_audit import COMPLETE_STATUSES, classify_bug
from src.extraction.bugsinpy import BugsInPyRepo


def bip_skip_reason(result: object) -> str:
    """One-line reason a BugsInPy bug is excluded from a pipeline stage."""
    status = getattr(result, "status", "unknown")
    if getattr(result, "error_msg", ""):
        return f"{status}: {result.error_msg}"  # type: ignore[attr-defined]
    unreached = getattr(result, "unreached_sigs", ())
    if status == "fl_unreachable" and unreached:
        return f"{status}: faulty method(s) not covered by spectra ({len(unreached)})"
    issues = getattr(result, "issues", [])
    errs = [i.get("message", "") for i in issues if i.get("severity") == "error"]
    if errs:
        return f"{status}: {errs[0]}"
    return str(status)


def classify_bip_bug(project: str, bug_id: str | int) -> tuple[object | None, str | None]:
    """Run the extraction completeness audit for a BugsInPy bug.

    Returns ``(result, skip_reason)``. ``skip_reason`` is set (and ``result`` may
    be ``None``) when the audit errors or the status is not in
    ``COMPLETE_STATUSES``; ``None`` means the bug passed the audit gate. Reads
    on-disk outputs only — no checkout needed.
    """
    repo = BugsInPyRepo(project, int(bug_id))
    try:
        result = classify_bug(repo)
    except Exception as exc:
        return None, f"audit failed: {exc!r}"
    if result.status not in COMPLETE_STATUSES:
        return result, bip_skip_reason(result)
    return result, None


def bip_corpus_exists(project: str, bug_id: str | int) -> bool:
    """True when the SR corpus (``FlexFL/SR/corpus_methods.txt``) exists on disk."""
    sr_dir = get_processed_dir(project, int(bug_id), dataset="bugsinpy") / FLEXFL_SR_SUBDIR
    return (sr_dir / "corpus_methods.txt").exists()


def bip_run_skip_reason(project: str, bug_id: str | int) -> str | None:
    """Return why a BugsInPy bug is not ready for ``run``/``combine``, else ``None``.

    Ready = extraction audit status in ``COMPLETE_STATUSES`` **and** the SR corpus
    exists (generated by the ``corpus`` subcommand). The ``run`` path additionally
    applies a blank-trigger skip at the call site; Agent4LR additionally requires the
    SR top-20 candidate list at the call site.
    """
    _, reason = classify_bip_bug(project, bug_id)
    if reason is not None:
        return reason
    if not bip_corpus_exists(project, bug_id):
        return "SR corpus missing (run the `corpus` subcommand first)"
    return None


__all__ = [
    "bip_corpus_exists",
    "bip_run_skip_reason",
    "bip_skip_reason",
    "classify_bip_bug",
]
