"""Per-API-call state machine for Agent4LR.

The sync runner (:mod:`src.agent4lr.agent`) and the batch workflow both
drive slot execution through the two functions here —
:func:`build_request` and :func:`apply_response` — so the transcript
construction (``input_list`` + human-readable ``messages``) has a single
implementation and cannot drift between the two paths.

One "step" is exactly one LLM API call plus its local consequences:

* **planner** — one step completes the slot.
* **tool_caller** — each step is one ReAct iteration: the deterministic
  ``"You have {remaining} tool calls remaining."`` reminder, the model
  response, local tool execution, and the appended observations. The
  slot completes on an ``exit`` call or budget exhaustion.
* **finisher** — one step: the deterministic handoff prompt, the model
  response, and extraction of the ``rank_methods`` indices.

Ephemeral pre-call messages (reminder/handoff) are regenerated by
:func:`build_request` and only persisted by :func:`apply_response`
together with the response items, so a :class:`PendingSlotState` never
holds a dangling prompt — resending a lost batch request is idempotent.

The state carried between steps is :class:`PendingSlotState`
(:mod:`src.agent4lr.checkpoints`); the sync runner keeps it in memory
only, while the batch workflow persists it between ticks.
"""

from __future__ import annotations

import logging
from collections.abc import Sequence
from dataclasses import dataclass, replace
from typing import Any

from src.agent4lr.agents import AgentSpec
from src.agent4lr.checkpoints import CompletedCheckpoint, PendingSlotState
from src.agent4lr.io import LRBugInputs
from src.agent4lr.prompts import (
    lr_finisher_user_prompt,
    lr_planner_user_prompt,
    lr_system_prompt,
    lr_tool_loop_user_prompt,
)
from src.agent4lr.providers import NormalisedResponse, ToolChoice
from src.agent4lr.tools import (
    LRToolContext,
    execute_tool,
    rank_methods,
    tool_schemas_finisher,
    tool_schemas_loop,
)

logger = logging.getLogger(__name__)

DEFAULT_TOOL_ITERATIONS = 10


@dataclass(frozen=True)
class PreparedRequest:
    """One ready-to-send LLM request for the slot a state is progressing.

    ``history`` is the canonical Responses-API-native input list
    *including* the regenerated ephemeral message (reminder/handoff)
    where the slot's role requires one. ``tools`` is in the nested shape
    emitted by :mod:`src.agent4lr.tools`, matching the ``Provider.chat``
    contract.
    """

    spec: AgentSpec
    history: list[dict[str, Any]]
    tools: list[dict[str, Any]] | None
    tool_choice: ToolChoice


@dataclass(frozen=True)
class AppliedStep:
    """Result of applying one response to a state.

    ``top5_indices`` is populated (possibly empty) only when a finisher
    slot completes; ``None`` otherwise.
    """

    state: PendingSlotState
    slot_completed: bool
    top5_indices: list[int] | None = None


def spec_from_identity(identity: dict[str, Any]) -> AgentSpec:
    """Reconstruct an :class:`AgentSpec` from its ``identity()`` dict."""
    return AgentSpec(**identity)


def tool_iter_budget(chain: Sequence[AgentSpec]) -> int:
    """Return the tool_caller slot's iteration budget for system-prompt rendering."""
    for spec in chain:
        if spec.role == "tool_caller" and spec.iterations is not None:
            return spec.iterations
    return DEFAULT_TOOL_ITERATIONS


def render_function_call_for_messages(name: str, arguments: dict[str, Any]) -> str:
    """Render a tool call as ``"[Function call: name(arg1, arg2)]"``.

    Matches FlexFL's ``process_response`` (``flexfl_pipeline.py:442``)
    so the human-readable transcript view stays byte-equivalent with
    the reference for matching tool-call arguments.
    """
    args_str = ", ".join(str(v) for v in arguments.values())
    return f"[Function call: {name}({args_str})]"


def extract_rank_methods_call(
    tool_calls: list[dict[str, Any]] | list[Any],
) -> list[int]:
    """Pull ``top_5_methods`` out of the finisher's structured tool call."""
    for tc in tool_calls:
        if tc.get("name") == "rank_methods":
            args = tc.get("arguments") or {}
            ids_raw = args.get("top_5_methods")
            if isinstance(ids_raw, list):
                out: list[int] = []
                for v in ids_raw:
                    if isinstance(v, bool):
                        continue
                    if isinstance(v, int):
                        out.append(v)
                    elif isinstance(v, float) and v.is_integer():
                        out.append(int(v))
                    elif isinstance(v, str):
                        try:
                            out.append(int(v.strip()))
                        except ValueError:
                            continue
                return out
    return []


# ---------------------------------------------------------------------------
# State construction
# ---------------------------------------------------------------------------


def initial_state(
    *,
    inputs_desc: dict[str, Any],
    inputs: LRBugInputs,
    chain: Sequence[AgentSpec],
) -> PendingSlotState:
    """Seed a fresh state at slot 0: system prompt + planner user prompt."""
    budget = tool_iter_budget(chain)
    system = lr_system_prompt(max_tool_calls=budget, inputs=inputs)
    user0 = lr_planner_user_prompt(inputs)
    seed = [
        {"role": "system", "content": system},
        {"role": "user", "content": user0},
    ]
    return PendingSlotState(
        inputs_descriptor=dict(inputs_desc),
        completed_chain=[],
        slot_spec=chain[0].identity(),
        calls_made=0,
        exited=False,
        input_list=[dict(m) for m in seed],
        messages=[dict(m) for m in seed],
        raw_responses=[],
    )


def state_for_slot(
    *,
    inputs_desc: dict[str, Any],
    chain: Sequence[AgentSpec],
    slot_index: int,
    ckpt: CompletedCheckpoint,
) -> PendingSlotState:
    """Fresh state for slot ``slot_index``, seeded from the previous slot's checkpoint.

    ``ckpt`` must be the completed checkpoint of ``chain[:slot_index]``.
    """
    return PendingSlotState(
        inputs_descriptor=dict(inputs_desc),
        completed_chain=[s.identity() for s in chain[:slot_index]],
        slot_spec=chain[slot_index].identity(),
        calls_made=0,
        exited=False,
        input_list=list(ckpt.input_list),
        messages=list(ckpt.messages),
        raw_responses=list(ckpt.raw_responses),
    )


# ---------------------------------------------------------------------------
# Step functions
# ---------------------------------------------------------------------------


def slot_is_complete(state: PendingSlotState) -> bool:
    """True when the state's slot needs no further LLM calls."""
    spec = spec_from_identity(state.slot_spec)
    if spec.role == "tool_caller":
        iters = spec.iterations or DEFAULT_TOOL_ITERATIONS
        return state.exited or state.calls_made >= iters
    return state.calls_made >= 1


def build_request(state: PendingSlotState) -> PreparedRequest:
    """Build the next LLM request for ``state``.

    Deterministic in the state: rebuilding after a lost/failed batch
    request yields a byte-identical request. Raises ``ValueError`` when
    the slot is already complete — callers must promote the state to a
    completed checkpoint instead.
    """
    if slot_is_complete(state):
        raise ValueError(
            f"build_request called on a completed slot "
            f"(role={state.slot_spec.get('role')!r}, calls_made={state.calls_made}, "
            f"exited={state.exited})"
        )
    spec = spec_from_identity(state.slot_spec)
    if spec.role == "planner":
        return PreparedRequest(
            spec=spec,
            history=list(state.input_list),
            tools=None,
            tool_choice="none",
        )
    if spec.role == "tool_caller":
        iters = spec.iterations or DEFAULT_TOOL_ITERATIONS
        reminder = {
            "role": "user",
            "content": lr_tool_loop_user_prompt(remaining=iters - state.calls_made),
        }
        return PreparedRequest(
            spec=spec,
            history=[*state.input_list, reminder],
            tools=tool_schemas_loop(),
            tool_choice="required",
        )
    if spec.role == "finisher":
        handoff = {"role": "user", "content": lr_finisher_user_prompt()}
        return PreparedRequest(
            spec=spec,
            history=[*state.input_list, handoff],
            tools=tool_schemas_finisher(),
            tool_choice="required",
        )
    raise ValueError(f"Unknown slot role {spec.role!r}")


def apply_response(
    state: PendingSlotState,
    resp: NormalisedResponse,
    ctx: LRToolContext,
) -> AppliedStep:
    """Apply one LLM response to ``state``: one complete step.

    Appends the same ephemeral message :func:`build_request` sent (so
    persisted transcripts stay byte-identical with the sync loop's),
    then the response items, the human-readable assistant mirror, and —
    for tool_caller steps — executes the returned tool calls locally and
    appends their observations.
    """
    if slot_is_complete(state):
        raise ValueError("apply_response called on a completed slot")
    spec = spec_from_identity(state.slot_spec)
    input_list = list(state.input_list)
    messages = list(state.messages)
    raw_responses = [*state.raw_responses, resp["raw"]]
    exited = state.exited
    top5_indices: list[int] | None = None

    if spec.role == "planner":
        input_list.extend(resp["new_items"])
        if resp["content"]:
            messages.append({"role": "assistant", "content": resp["content"]})
    elif spec.role == "tool_caller":
        iters = spec.iterations or DEFAULT_TOOL_ITERATIONS
        reminder = {
            "role": "user",
            "content": lr_tool_loop_user_prompt(remaining=iters - state.calls_made),
        }
        input_list.append(dict(reminder))
        messages.append(dict(reminder))
        input_list.extend(resp["new_items"])

        tcs = resp["tool_calls"]
        # Human-readable assistant entry: any text plus a
        # "[Function call: ...]" synthetic line per tool call.
        pieces: list[str] = []
        if resp["content"]:
            pieces.append(resp["content"])
        for tc in tcs:
            pieces.append(render_function_call_for_messages(tc["name"], tc["arguments"]))
        if pieces:
            messages.append({"role": "assistant", "content": "\n".join(pieces)})

        # A response with no tool calls still consumes the iteration.
        if tcs:
            for tc in tcs:
                tool_output = execute_tool(ctx=ctx, name=tc["name"], args=tc["arguments"])
                call_id = tc.get("call_id") or ""
                input_list.append(
                    {
                        "type": "function_call_output",
                        "call_id": call_id,
                        "output": tool_output,
                    }
                )
                messages.append({"role": "user", "content": tool_output})
            if any(tc["name"] == "exit" for tc in tcs):
                logger.debug(
                    "Agent4LR %s-%s: tool-loop exited at iteration %d/%d",
                    ctx.project,
                    ctx.bug_id,
                    state.calls_made + 1,
                    iters,
                )
                exited = True
        if not exited and state.calls_made + 1 >= iters:
            logger.debug("Agent4LR %s-%s: tool-loop budget exhausted", ctx.project, ctx.bug_id)
    elif spec.role == "finisher":
        handoff = {"role": "user", "content": lr_finisher_user_prompt()}
        input_list.append(dict(handoff))
        messages.append(dict(handoff))
        input_list.extend(resp["new_items"])

        tcs = resp["tool_calls"]
        top5_indices = extract_rank_methods_call(tcs)

        pieces = []
        if resp["content"]:
            pieces.append(resp["content"])
        for tc in tcs:
            pieces.append(render_function_call_for_messages(tc["name"], tc["arguments"]))
        if pieces:
            messages.append({"role": "assistant", "content": "\n".join(pieces)})

        if top5_indices:
            resolved = rank_methods(ctx=ctx, top_5_methods=top5_indices)
            top_n_block = "\n".join(f"Top_{i} : {fqn}" for i, fqn in enumerate(resolved, start=1))
            if top_n_block:
                messages.append({"role": "user", "content": top_n_block})
    else:  # pragma: no cover — validate_v1_invariant rules this out upstream
        raise ValueError(f"Unknown slot role {spec.role!r}")

    new_state = replace(
        state,
        calls_made=state.calls_made + 1,
        exited=exited,
        input_list=input_list,
        messages=messages,
        raw_responses=raw_responses,
    )
    return AppliedStep(
        state=new_state,
        slot_completed=slot_is_complete(new_state),
        top5_indices=top5_indices,
    )


__all__ = [
    "DEFAULT_TOOL_ITERATIONS",
    "AppliedStep",
    "PreparedRequest",
    "apply_response",
    "build_request",
    "extract_rank_methods_call",
    "initial_state",
    "render_function_call_for_messages",
    "slot_is_complete",
    "spec_from_identity",
    "state_for_slot",
    "tool_iter_budget",
]
